- name: Deploy web app via Docker container
  hosts: all
  become: yes  

  tasks:
    - name: Install Docker
      ansible.builtin.package:
        name: docker
        state: present

    - name: Pull Docker image
      community.docker.docker_image:
        name: "gilibee/hailyeah:latest"
        source: pull
        force_source: yes
        

    - name: Install Cosign
      shell: |
        wget https://github.com/sigstore/cosign/releases/download/v1.5.2/cosign-linux-amd64 -O cosign
        chmod +x cosign
        sudo mv cosign /usr/local/bin/


    - name: Copy Cosign pub key
      copy:
        src: ./cosign/cosign.pub
        dest: /home/ubuntu
        owner: ubuntu
        group: ubuntu
        mode: '0644'


    - name: Run Cosign Verify
      shell: |
        pwd
        cosign-linux-amd64 verify --key cosign.pub gilibee/hailyeah:latest

    - name: Stop previous Docker container
      community.docker.docker_container:
        name: hailyeah_app
        state: absent

    - name: Launch the new Docker container
      community.docker.docker_container:
        name: hailyeah_app
        image: "gilibee/hailyeah:latest"
        state: started
        ports:
          - "80:80" 
        volumes:
          - hailyeah-logs:/app/logs
        restart_policy: always
 
