name: Hailyeah_deplopy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Build image
        # working-directory: /home/runner/work/
        
        run: |
          pwd
          docker build -t gilibee/hailyeah:latest .


      - name: Save ansible to cache
        uses: actions/upload-artifact@v4
        with:
          name: ansible-deployment
          path: /home/runner/work/Ansible/ansible_deploy.yml


      - name: Push image to Dockerhub
        run: docker push gilibee/hailyeah:latest
