name: Hailyeah_deplopy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  snyk-python-docker-lint:
    runs-on: ubuntu-latest
    steps:
    
    
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cat requirements.txt | xargs -n 1 pip install || true
      
      - name: Run Snyk to check for Python modules vulnerabilities
        uses: snyk/actions/python-3.8@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=critical

      - name: Run Snyk to check Docker images for vulnerabilities
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: gilibee/hailyeah:latest
          args: --file=Dockerfile --severity-threshold=high
          
          
      - name: Install linter
        run: |
          python -m pip install --upgrade pip
          pip install flake8  # Install flake8 linter
              
      - name: Run Static Code Analysis
        run: |
          flake8 --max-line-length 120 ./Python/



  build:
    runs-on: ubuntu-latest

    needs: [snyk-python-docker-lint]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Build image
        # working-directory: /home/runner/work/
        
        run: |
          pwd
          docker build -t gilibee/hailyeah:latest .


      - name: Save ansible to cache
        uses: actions/upload-artifact@v4
        with:
          name: ansible-deployment
          path: /home/runner/work/Ansible/*


      - name: Push image to Dockerhub
        run: docker push gilibee/hailyeah:latest
        
        

  deploy:
    runs-on: ubuntu-latest

    needs: [build]

    steps:
      - name: Checkout Ansible playbook
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            Ansible/ansible_deploy.yml
          sparse-checkout-cone-mode: false
    
    
      - name: Install and configure aws cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
          verbose: false
          arch: amd64
      - run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region ${{ secrets.AWS_REGION }}

      - name: get deployment servers
        run: |
          echo "Deployment_Servers=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=HailYeah_Deploy" --query "Reservations[*].Instances[*].PublicIpAddress" --output text)" >> $GITHUB_ENV

#      - name: Download ansible artifact
#        uses: actions/download-artifact@v4
#        with:
#          name: ansible_deploy

      - name: Output SSH key to file
        run: |
          mkdir ~/.ssh
          echo "${{secrets.DEPLOYMENT_SSH_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy via ansible
        run: |
          pwd
          ls
          export ANSIBLE_HOST_KEY_CHECKING=False
          echo "Hailyeah ansible_host=16.171.25.204 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa" > hosts_github
          ansible-playbook ./Ansible/ansible_deploy.yml -i hosts_github
          
          
          
          
          
          
